### ISSUE TITLE
Boot Crash with Essential

### ISSUE THREAD

**Issue by Afrocntrik** [astei/krypton#57] opened 2021-12-22 17:48 UTC
This a multiplayer mod that injects right before launching the game to overwrite the multiplayer system. That's from my understanding. [Essential](https://www.curseforge.com/minecraft/mc-mods/essential-mod)
[latest.log](https://github.com/astei/krypton/files/7764330/latest.log)
)

**Comment by astei** [comment] 2021-12-22 18:16
The mod has no source code available and your log is incomplete

**Comment by SystemlessDev** [comment] 2021-12-23 21:03
Hey! Systemless from the Essential support team here. No one on our team is able to reproduce this issue. And if it anyone's issue I'd most likely assume it would fall onto us. Would you be able to join our discord server at discord.gg/essential and create a ticket so that we can look at this issue properly? 

And for reference we don't overwrite the multiplayer system :) 
We try to be as compatible as possible with every mod out there.

**Comment by astei** [comment] 2021-12-24 00:24
Closing because I can't see how this is an issue in Krypton

**Closed by astei** 2021-12-24 00:24 UTC
