### ISSUE TITLE
Client side memory leak with Direct Buffers

### ISSUE THREAD

**Issue by aria1th** [astei/krypton#63] opened 2022-03-05 13:39 UTC
I checked this with MemoryMXBean Direct pool size check.
Krypton does not release direct buffers in client side. 
It happens when BlockEntityData is fully sent to client, which is usually non-vanilla behavior.
Direct Buffer Pool will increase size until it reaches memory limit, and OutOfMemory occurs, directly or indirectly if other mods are using direct memory allocation.

**Comment by astei** [comment] 2022-03-05 18:01
Without a reproducer case I will not be able to take action. I am skeptical that this is a bug in Krypton.

**Comment by aria1th** [comment] 2022-03-06 11:16
https://user-images.githubusercontent.com/35677394/156920682-f7319d18-f4e6-4ebd-bcb8-2c9e5b2a436f.mp4


https://user-images.githubusercontent.com/35677394/156920686-b7f4e2c0-c047-4072-a613-f7fef66d274d.mp4

it eats 4MB of buffer every 3 seconds with krypton. The only difference is krypton...
Also its directbuffer pool size is from IRIS
https://github.com/IrisShaders/Iris/blob/1.18/src/main/java/net/coderbot/iris/mixin/MixinDebugScreenOverlay.java

**Comment by astei** [comment] 2022-03-06 18:04
Well, Krypton sets a lower size for Netty buffer areas - 4MiB instead of the default 16MiB. This by itself explains the allocations being exactly 4MiB. The evidence you've provided means nothing except for the mod working as intended - it doesn't even necessarily show a memory leak.

I'm happy to further debug this issue, but the evidence you've provided me doesn't mean anything.

**Comment by aria1th** [comment] 2022-03-07 06:15
sadly it accumulates over and over... until it reaches 32GB and more and crash...
![2022-03-01_21 33 23](https://user-images.githubusercontent.com/35677394/156977679-4a054977-69c6-4de8-9aa3-83288fb33c1c.png)
 I'll check if setting ResourceLeakDetector.Level.ADVANCED solves this

**Comment by astei** [comment] 2022-03-09 04:34
Managed to reproduce. As it turns out, Minecraft disables the Netty resource leak detector early in initialization and you need to use a mixin to make it not do that. I've fixed this and it identified the leak straight away. Working on a fix.

**Comment by astei** [comment] 2022-03-09 04:52
Resolved in bcde15606936fc15503f53f591c1f5b3c8da51b7, will release 0.1.8 with the fix.

**Closed by astei** 2022-03-09 04:52 UTC
Labels: bug
