### ISSUE TITLE
Mixin apply failure on 1.17.1 RC 2 server

### ISSUE THREAD

**Issue by QPCrummer** [astei/krypton#35] opened 2021-07-06 03:04 UTC
Here is the crash report on the server with the latest Krypton: https://pastebin.com/9iyG8BwK

**Comment by QPCrummer** [comment] 2021-07-06 03:05
sorry if this is already a known issue.

**Comment by astei** [comment] 2021-07-06 03:05
Already fixed in #34

**Comment by QPCrummer** [comment] 2021-07-06 03:06
It isn't fixed. I am using that version

**Closed by astei** 2021-07-06 03:05 UTC

**Comment by astei** [comment] 2021-07-06 03:06
Tested locally, it works fine. You probably have an old version of Krypton lurking on your server.

**Comment by QPCrummer** [comment] 2021-07-06 03:06
This version right here: https://github.com/astei/krypton/tree/1ae22c746511246fa67d99fa970aa6d5180ca58a

**Comment by QPCrummer** [comment] 2021-07-06 03:09
Nope, I just tested with that krypton right there ^ and FAPI. It gave the same error. I am using FAPI 36.1.

**Comment by astei** [comment] 2021-07-06 03:11
I am unable to reproduce the issue on my system, even with Fabric API 0.36.1. Check if you have multiple versions of Krypton on the system and make sure you actually have the latest version of Krypton installed.

**Comment by QPCrummer** [comment] 2021-07-06 14:12
Ok, I am still getting the crash with the latest 0.1.4 snapshot version of krypton. I tested without FAPI and the crash still happens. I made sure to turn all other servers off and delete all mods in my mods folder except for krypton. I am also running 1.17.1 now.

**Comment by QPCrummer** [comment] 2021-07-06 14:15
Ok, after deleting the .fabric and .mixin.out folders, it runs smoothly. Thanks for helping me
