### ISSUE TITLE
Chat causes stutter in clients with Krypton

### ISSUE THREAD

**Issue by ccrvincent** [astei/krypton#59] opened 2022-01-06 16:06 UTC
**My Client:**  1.18.1 Fabric w/ Fabulously Optimized 3.1.0-alpha.6 + Simple Voice Chat 2.1.28
**Server:** 1.18.1 Fabric 0.12.12

**Server Mods**
Dynmap 3.3-beta-4
Fabric API 0.45.0
Ferrite Core 4.0.0
Krypton 0.1.6
LazyDFU 0.1.2
Lithium 0.7.7
Phosphor 0.8.1
SmoothBoot 1.7.0
Spark
Simple Voice Chat 2.1.28

**Server Datapacks**
All from Vanilla Tweaks:
AFK Display 1.1.2
Anti Enderman Grief 1.1.2
Armor Statues 2.8.3
Cauldron Concrete 2.0.5
Coordinates HUD 1.2.2
Durability Ping 1.1.2
Graves 2.8.5
More Mob Heads 2.9.4
Multiplayer Sleep 2.6.2
Nether Portal Coordinates 1.1.2
Player Head Drops 1.1.2
Silence Mobs 1.1.2
Track Raw Statistics 1.5.2
Track Statistics 1.1.3
Wandering Trades 1.5.1

With Krypton installed and enabled at the server, every text chat message caused visible stuttering of all clients.  Disabling Krypton fixed the stuttering.  There were no corresponding log messages, TPS lag, etc.

I know it's super vague, but it appeared to be unreported and we were able to A/B confirm it only happened with Krypton enabled.

**Comment by ccrvincent** [comment] 2022-01-06 16:19
I'd have to go back and double-check, but I _think_ Coordinates HUD was also blinking in and out with Krypton enabled.

**Comment by Kichura** [comment] 2022-01-06 18:37
Can confirm as krypton causes lag spikes on specific msg begins - And it can get annoying overtime when playing on servers that you chat alot in,

I can also reproduce this problem in my own modpack aswell and it really is not great for proper optimization.

**Comment by astei** [comment] 2022-01-08 22:29
I'm not able to reproduce this. Please provide clear reproduction steps and any client profiles.

**Comment by ccrvincent** [comment] 2022-01-09 00:14
It looks like it might just be Krypton somehow making https://bugs.mojang.com/browse/MC-247973 more severe, not something entirely unique to Krypton?

Re-adding Krypton later was fine, which reinforces the external cause hypothesis.

**Comment by astei** [comment] 2022-01-09 00:15
I'm closing this as a Mojang issue then. Krypton doesn't touch anything related to chat.

**Closed by astei** 2022-01-09 00:15 UTC
Labels: bug

**Comment by Kichura** [comment] 2022-01-10 17:32
Update to this issue: The issue has been resolved but was moved to WEB-5587 as it was an API issue and not minecraft clients themselves.
